CREATE TABLE IF NOT EXISTS `content_user_growth_penalty_record` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `user_id` varchar(32) NOT NULL COMMENT '用户ID',
  `governance_record_id` varchar(32) DEFAULT NULL COMMENT '治理状态记录ID',
  `appeal_id` varchar(32) DEFAULT NULL COMMENT '关联申诉ID',
  `source_type` varchar(64) DEFAULT NULL COMMENT '处罚来源类型',
  `source_id` varchar(64) DEFAULT NULL COMMENT '处罚来源业务主键',
  `source_status` varchar(64) DEFAULT NULL COMMENT '处罚来源状态快照',
  `penalty_type` varchar(32) NOT NULL COMMENT '处罚类型',
  `effect_snapshot_json` text NOT NULL COMMENT '处罚影响快照JSON',
  `status` varchar(32) NOT NULL DEFAULT 'PENDING_RECOVER' COMMENT '恢复状态',
  `recover_trigger` varchar(64) DEFAULT NULL COMMENT '恢复触发来源',
  `recover_reason` varchar(255) DEFAULT NULL COMMENT '恢复原因',
  `recovered_by` varchar(32) DEFAULT NULL COMMENT '恢复操作人',
  `recovered_at` datetime DEFAULT NULL COMMENT '恢复时间',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_content_user_growth_penalty_user` (`user_id`,`status`,`create_time`),
  KEY `idx_content_user_growth_penalty_governance` (`governance_record_id`,`status`),
  KEY `idx_content_user_growth_penalty_appeal` (`appeal_id`,`status`),
  KEY `idx_content_user_growth_penalty_source` (`source_type`,`source_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='内容社区成长处罚恢复记录';
